=== ihlys/musicstore/src/test/resources/repository/schema/test-data-schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.musicstore.com"
           xmlns="https://www.musicstore.com"
           elementFormDefault="qualified">

    <xs:include schemaLocation="test-data-types-schema.xsd"/>

    <xs:element name="dataset">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element name="LANGUAGE" type="Language"/>

                <xs:element name="SONG" type="Song"/>
                <xs:element name="SONGS_LOCALIZED_DATA" type="SongsLocalizedData"/>
                <xs:element name="ALBUM" type="Album"/>
                <xs:element name="ALBUMS_LOCALIZED_DATA" type="AlbumsLocalizedData"/>
                <xs:element name="ARTIST" type="Artist"/>
                <xs:element name="ARTISTS_LOCALIZED_DATA" type="ArtistsLocalizedData"/>
                <xs:element name="GENRE" type="Genre"/>
                <xs:element name="GENRES_LOCALIZED_DATA" type="GenresLocalizedData"/>
                <xs:element name="THEMATIC_COLLECTION" type="ThematicCollection"/>
                <xs:element name="THEMATIC_COLLECTIONS_LOCALIZED_DATA" type="ThematicCollectionsLocalizedData"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ihlys/musicstore/src/test/resources/repository/data/song-repository/find-songs-by-genre-id-projected-paginated-source-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns="https://www.musicstore.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.musicstore.com ../../schema/test-data-schema.xsd">

    <GENRE id="1"/>
        <GENRE id="2" parent_genre_id="1"/>
            <GENRE id="3" parent_genre_id="2"/>
                <ARTIST id="1" genre_id="3"/>
                    <ALBUM id="1" artist_id="1" release_date="2017-05-25" album_type="STUDIO_ALBUM"/>
                        <SONG id="1" album_id="1"/>
                        <SONG id="2" album_id="1"/>
                    <ALBUM id="2" artist_id="1" release_date="2017-05-25" album_type="STUDIO_ALBUM"/>
                        <SONG id="3" album_id="2"/>
                        <SONG id="4" album_id="2"/>
                        <SONG id="5" album_id="2"/>
            <GENRE id="4" parent_genre_id="2"/>
                <ARTIST id="2" genre_id="4"/>
                    <ALBUM id="3" artist_id="2" release_date="2017-05-25" album_type="STUDIO_ALBUM"/>
                        <SONG id="6" album_id="3"/>
                        <SONG id="7" album_id="3"/>
                        <SONG id="8" album_id="3"/>
                <ARTIST id="3" genre_id="4"/>
                    <ALBUM id="4" artist_id="3" release_date="2017-05-25" album_type="STUDIO_ALBUM"/>
                        <SONG id="9" album_id="4"/>

</dataset>

=== ihlys/musicstore/src/test/resources/repository/data/test-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns="https://www.musicstore.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.musicstore.com ../schema/test-data-schema.xsd">

    <GENRE id="1" />
        <ARTIST id="1" genre_id="1"/>
            <ALBUM id="1" artist_id="1"/>
                <SONG id="1" album_id="1" />
                <SONG id="2" album_id="1" />
                <SONG id="3" album_id="1" />
            <ALBUM id="2" artist_id="1"/>
                <SONG id="4" album_id="2" />
                <SONG id="5" album_id="2" />
                <SONG id="6" album_id="2" />
        <ARTIST id="2" genre_id="1"/>
            <ALBUM id="3" artist_id="2"/>
                <SONG id="7" album_id="3" />
                <SONG id="8" album_id="3" />
                <SONG id="9" album_id="3" />
            <ALBUM id="4" artist_id="2"/>
                <SONG id="10" album_id="4" />
                <SONG id="11" album_id="4" />
                <SONG id="12" album_id="4" />

    <LANGUAGE id="1" name="EN" />
    <LANGUAGE id="2" name="RU" />

    <GENRES_LOCALIZED_DATA id="1" genre_id="1" language_id="1"
                           name="Rock" description="This is rock music"/>
    <GENRES_LOCALIZED_DATA id="2" genre_id="1" language_id="2"
                           name="Рок" description="Это рок музыка"/>

    <ARTISTS_LOCALIZED_DATA id="1" artist_id="1" language_id="1"
                            name="Nightwish" description="This is Nightwish band"/>
    <ARTISTS_LOCALIZED_DATA id="2" artist_id="1" language_id="2"
                            name="Nightwish" description="Это группа Nightwish"/>
    <ARTISTS_LOCALIZED_DATA id="3" artist_id="2" language_id="1"
                            name="Disturbed" description="This is Disturbed band"/>
    <ARTISTS_LOCALIZED_DATA id="4" artist_id="2" language_id="2"
                            name="Disturbed" description="Это группа Disturbed"/>

    <ALBUMS_LOCALIZED_DATA id="1" album_id="1" language_id="1"
                           name="Oceanborn" description="This is Oceanborn album"/>
    <ALBUMS_LOCALIZED_DATA id="2" album_id="1" language_id="2"
                           name="Oceanborn" description="Это альбом Oceanborn"/>
    <ALBUMS_LOCALIZED_DATA id="3" album_id="2" language_id="1"
                           name="Wishmaster" description="This is Wishmaster album"/>
    <ALBUMS_LOCALIZED_DATA id="4" album_id="2" language_id="2"
                           name="Wishmaster" description="Это альбом Wishmaster"/>
    <ALBUMS_LOCALIZED_DATA id="5" album_id="3" language_id="1"
                           name="Indestructible" description="This is Indestructible album"/>
    <ALBUMS_LOCALIZED_DATA id="6" album_id="3" language_id="2"
                           name="Indestructible" description="Это альбом Indestructible"/>
    <ALBUMS_LOCALIZED_DATA id="7" album_id="4" language_id="1"
                           name="Asylum" description="This is Asylum album"/>
    <ALBUMS_LOCALIZED_DATA id="8" album_id="4" language_id="2"
                           name="Asylum" description="Это альбом Asylum"/>

    <SONGS_LOCALIZED_DATA id="1"  song_id="1"  language_id="1" name="The Pharao Sails to Orion"/>
    <SONGS_LOCALIZED_DATA id="2"  song_id="2"  language_id="1" name="Devil &amp; the Deep Dark Ocean"/>
    <SONGS_LOCALIZED_DATA id="3"  song_id="3"  language_id="1" name="Moondance"/>
    <SONGS_LOCALIZED_DATA id="4"  song_id="4"  language_id="1" name="Wishmaster"/>
    <SONGS_LOCALIZED_DATA id="5"  song_id="5"  language_id="1" name="The Kinslayer"/>
    <SONGS_LOCALIZED_DATA id="6"  song_id="6"  language_id="1" name="Wanderlust"/>
    <SONGS_LOCALIZED_DATA id="7"  song_id="7"  language_id="1" name="Indestructible"/>
    <SONGS_LOCALIZED_DATA id="8"  song_id="8"  language_id="1" name="Inside the Fire"/>
    <SONGS_LOCALIZED_DATA id="9"  song_id="9"  language_id="1" name="The Night"/>
    <SONGS_LOCALIZED_DATA id="10" song_id="10" language_id="1" name="Asylum"/>
    <SONGS_LOCALIZED_DATA id="11" song_id="11" language_id="1" name="The Animal"/>
    <SONGS_LOCALIZED_DATA id="12" song_id="12" language_id="1" name="The Infection"/>

</dataset>

=== ihlys/musicstore/src/test/resources/repository/data/artist-repository/find-artists-by-genre-id-projected-paginated-source-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset xmlns="https://www.musicstore.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://www.musicstore.com ../../schema/test-data-schema.xsd">

    <GENRE id="1"/>
        <GENRE id="2" parent_genre_id="1"/>
            <GENRE id="3" parent_genre_id="2"/>
                <ARTIST id="1" genre_id="3"/>
                <ARTIST id="2" genre_id="3"/>
                <ARTIST id="3" genre_id="3"/>
            <GENRE id="4" parent_genre_id="2"/>
                <ARTIST id="4" genre_id="4"/>

</dataset>
